//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaDoZe.Presentation.AppMaui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaDoZe.Presentation.AppMaui.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aluno ID.
        /// </summary>
        internal static string strAlunoIdLabel {
            get {
                return ResourceManager.GetString("strAlunoIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alunos.
        /// </summary>
        internal static string strAlunos {
            get {
                return ResourceManager.GetString("strAlunos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        internal static string strCancelar {
            get {
                return ResourceManager.GetString("strCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colaboradores.
        /// </summary>
        internal static string strColaboradores {
            get {
                return ResourceManager.GetString("strColaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colaborador ID.
        /// </summary>
        internal static string strColaboradorIdLabel {
            get {
                return ResourceManager.GetString("strColaboradorIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string strConfiguracoes {
            get {
                return ResourceManager.GetString("strConfiguracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credenciais do Banco.
        /// </summary>
        internal static string strCredenciaisBanco {
            get {
                return ResourceManager.GetString("strCredenciaisBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados de Trabalho.
        /// </summary>
        internal static string strDadosTrabalho {
            get {
                return ResourceManager.GetString("strDadosTrabalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dashboard.
        /// </summary>
        internal static string strDashboard {
            get {
                return ResourceManager.GetString("strDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Aluno.
        /// </summary>
        internal static string strEditarAluno {
            get {
                return ResourceManager.GetString("strEditarAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Colaborador.
        /// </summary>
        internal static string strEditarColaborador {
            get {
                return ResourceManager.GetString("strEditarColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string strEditarLabel {
            get {
                return ResourceManager.GetString("strEditarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Logradouro.
        /// </summary>
        internal static string strEditarLogradouro {
            get {
                return ResourceManager.GetString("strEditarLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Matrícula.
        /// </summary>
        internal static string strEditarMatricula {
            get {
                return ResourceManager.GetString("strEditarMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string strExcluirLabel {
            get {
                return ResourceManager.GetString("strExcluirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouros.
        /// </summary>
        internal static string strLogradouros {
            get {
                return ResourceManager.GetString("strLogradouros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrícula ID.
        /// </summary>
        internal static string strMatriculaIdLabel {
            get {
                return ResourceManager.GetString("strMatriculaIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrículas.
        /// </summary>
        internal static string strMatriculas {
            get {
                return ResourceManager.GetString("strMatriculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Primeiro Aluno.
        /// </summary>
        internal static string strNenhumAlunoButton {
            get {
                return ResourceManager.GetString("strNenhumAlunoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum aluno encontrado.
        /// </summary>
        internal static string strNenhumAlunoLabel {
            get {
                return ResourceManager.GetString("strNenhumAlunoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Primeiro Colaborador.
        /// </summary>
        internal static string strNenhumColaboradorButton {
            get {
                return ResourceManager.GetString("strNenhumColaboradorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum colaborador encontrado.
        /// </summary>
        internal static string strNenhumColaboradorLabel {
            get {
                return ResourceManager.GetString("strNenhumColaboradorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Primeiro Matrícula.
        /// </summary>
        internal static string strNenhumMatriculaButton {
            get {
                return ResourceManager.GetString("strNenhumMatriculaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novo Aluno.
        /// </summary>
        internal static string strNovoAlunoTitulo {
            get {
                return ResourceManager.GetString("strNovoAlunoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novo Colaborador.
        /// </summary>
        internal static string strNovoColaboradorTitulo {
            get {
                return ResourceManager.GetString("strNovoColaboradorTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço.
        /// </summary>
        internal static string strPalavraEndereco {
            get {
                return ResourceManager.GetString("strPalavraEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string strSalvar {
            get {
                return ResourceManager.GetString("strSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecionar Imagem.
        /// </summary>
        internal static string strSelecionarImagem {
            get {
                return ResourceManager.GetString("strSelecionarImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sistema de Gerenciamento.
        /// </summary>
        internal static string strSubtituloAplicacao {
            get {
                return ResourceManager.GetString("strSubtituloAplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tema.
        /// </summary>
        internal static string strTema {
            get {
                return ResourceManager.GetString("strTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Academia do Pet.
        /// </summary>
        internal static string strTituloAplicacao {
            get {
                return ResourceManager.GetString("strTituloAplicacao", resourceCulture);
            }
        }
    }
}
